export { default as bachhoa } from './image/bach-hoa.png';
export { default as danhchoban } from './image/danh-cho-ban.png';
export { default as dealsieuhot } from './image/deal-sieu-hot.png';
export { default as hangmoi } from './image/hang-moi.png';
export { default as revodoi } from './image/re-vo-doi.png';
export { default as logo } from './logo/logo.png'
export { default as logoFb } from './logo/logoFb.png';
export { default as logoGoogle } from './logo/logoGoogle.png';
export { default as dealFlashIcon } from './logo/dealFlashIcon.svg';
export { default as dogcute } from './image/dogcute.jpg';
export { default as noUser } from './image/noUser.png';
export { default as fire_icon } from './logo/fire_icon.svg';
export { default as logo_dpshopvn } from './logo/logo_dpshopvn.png';
